### ISSUE TITLE
What is the hardware used to fine tune SciBERT using NLI datasets?

### ISSUE THREAD

**Issue by kalyanks0611** [gsarti/covid-papers-browser#2]
Its a nice work. I would like to know the following details @gsarti 
a)Which GPU you have used to fine-tune SciBERT?
b) How much time did it take as a whole to fine SciBERT using NLI and MNLI datasets?

**Comment by gsarti** [comment]
Hi, thank you and sorry that those details were not provided! I will take care of adding those in the README file asap.

a) I did the fine-tuning on a Kaggle notebook using the standard GPU
b) It took around 4 hours for 20000 steps at batch size 64.

Hope this helps!
